title: ERCT - Educational RCT Standard
email: vassiliphilippov@gmail.com
description: >-
  The Educational Randomized Controlled Trial (ERCT) Standard is a 
  rigorous framework addressing key challenges in educational studies. 
  With 12 criteria across 3 progressive levels, it resolves issues like 
  bias, limited scope, and short-term focus, enabling researchers 
  to produce actionable results that improve education systems worldwide
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://erct-papers.com" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Collections
collections:
  papers:
    output: true  # This generates a page for each paper


defaults:
  - scope:
      path: "_papers"    # More specific path
      type: "papers"
    values:
      layout: "paper"

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
